# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

#beta lane is just to build app
 	lane :beta do
	build_app(scheme: "Runner",
            workspace: "Runner.xcworkspace",
            include_bitcode: true)
	end

# created following releaase lane to have automatic sign and provisioning profile from xCode set up - Nag
 	lane :release do
	gym(
        scheme: "Runner",
        archive_path: "build/Runner.xcarchive",
        output_directory: "build/",
        output_name: "AmericanEssentials.ipa",
        destination: "generic/platform=iOS",
        export_method: "development",
        export_xcargs: "-allowProvisioningUpdates",
     )

#this below code can be used once we have git repository built for certificates at enterprise level.. this will help is easier handling of certs
#  		sync_code_signing
#  		disable_automatic_code_signing(path: "Runner.xcodeproj")
#  		build_app(scheme: "Runner",
#            		   workspace: "Runner.xcworkspace",
#            		   include_bitcode: true)
#  		enable_automatic_code_signing(path: "Runner.xcodeproj")
#  		upload_to_testflight
		end
    # add actions here: https://docs.fastlane.tools/actions
  end
end
