name: aae
description: American Airlines - AA Essentials

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 9.9.9+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_webview_plugin:
    path: ./fwplugin
  corsac_jwt: ^0.3.0
  mockito: ^4.1.1
  html: ^0.14.0+4
  shared_preferences: ^0.5.12+2
  built_value_generator: ^7.1.0
  built_collection: ^4.3.2
  url_launcher: ^5.7.6
  intl: ^0.16.1
  logging: ^0.11.4
  local_auth: ^0.6.3+3
  flutter_secure_storage: ^3.3.5
  platform: ^2.2.1
  flutter_widgets: ^0.1.12
  webview_flutter: ^1.0.7
  flutter_html: ^1.0.2
  gradient_app_bar: ^0.1.3
  cached_network_image: ^2.2.0+1
  flutter_keyboard_visibility: ^0.7.0
  keyboard_avoider: ^0.1.2
  flutter_svg: ^0.18.0
  link: ^1.0.0
  recase: ^3.0.0
  date_picker_timeline: ^1.2.1
  slider_button: ^0.6.0
  expandable: ^4.1.4
  custom_switch_button: ^0.5.0
  custom_switch: ^0.0.1
  flutter_switch: ^0.1.5
  flutter_widget_from_html: ^0.5.1+3
  linkable: ^1.0.4
  date_format: ^1.0.9
  dotted_line: ^2.0.2
  flutter:
    sdk: flutter
  firebase_core: ^0.5.2
  firebase_crashlytics: ^0.2.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the Cupertino Icons class for iOS style icons.
  cupertino_icons: ^0.1.2

dependency_overrides:
  webview_flutter: ^0.3.22+1

dev_dependencies:
  built_value: ^7.1.0
  build_runner: ^1.10.1
  inject:
    path: ./inject/inject.dart/package/inject/
  inject_generator:
    path: ./inject/inject.dart/package/inject_generator
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/common/
    - assets/svg/
    - assets/static_records/RecognitionHistory.json
    - assets/static_records/FlightSearch.json
    - assets/static_records/image.jpeg
    - assets/common/sign_in_background.png
    - assets/raw/imageserverbase64.cer

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: AmericanSans
      fonts:
        - asset: assets/fonts/AmericanSans-Regular.ttf
        - asset: assets/fonts/AmericanSans-Italic.ttf
          style: italic
        - asset: assets/fonts/AmericanSans-Bold.ttf
        - asset: assets/fonts/AmericanSans-BoldItalic.ttf
    - family: AmericanSansMedium
      fonts:
        - asset: assets/fonts/AmericanSans-Medium.otf
        - asset: assets/fonts/AmericanSans-MediumItalic.otf
          style: italic
    - family: AmericanSansLight
      fonts:
        - asset: assets/fonts/AmericanSans-Light.ttf
        - asset: assets/fonts/AmericanSans-LightItalic.ttf
          style: italic
    - family: AaeIcons
      fonts:
        - asset: assets/fonts/AaeIcons.ttf
    - family: AmericanIconsv4_6
      fonts:
        - asset: assets/fonts/AmericanIconsv4.6-Regular.otf

