/// This file was generated by script using the [component-generate] command
/// you can remove this heading once you have added a reference to this class
/// to UnmodifiableListView<ProvidedService> services found in [mobile_module.dart]

import 'dart:collection';
import 'dart:convert';

import 'package:aae/api/api_client.dart';
import 'package:aae/cache/cache_service.dart';
import 'package:aae/common/repository/repository.dart';
import 'package:aae/model/serializers.dart';
import 'package:aae/rx/rx_util.dart';
import 'package:aae/rxdart/rx.dart';
import 'package:inject/inject.dart';
import 'package:logging/logging.dart';

class TravelTravelRepository implements Repository {
  static final _log = Logger(Repository.buildLogName('TravelTravelRepository'));

  static const cacheKey = 'TravelTravelRepository.Events';

  @provide
  @singleton
  TravelTravelRepository(/* Add dependancies here*/);

  @override
  void start() {} // NO-OP
  @override
  void stop() {} // NO-OP
  @override
  void clear() {} // NO-OP
}
