#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/200989/dev/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/200989/dev_projects/american-essentials/essentials-ui/aae_mobile"
export "FLUTTER_TARGET=/Users/200989/dev_projects/american-essentials/essentials-ui/aae_mobile/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/200989/dev/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_ROOT=/Users/nagarajhiremath/development/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/nagarajhiremath/Documents/AmericanEssentials_mycode/essentials-ui/aae_mobile"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/nagarajhiremath/development/flutter/bin/cache/artifacts/engine/ios-release"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
