name: Build iOS

on:
  push:
    branches:
      - features/gitHubActions-iosFastlane-POC
      - develop
      - development
      - features/*
      - features/firebasearticleevent

jobs:
    build:
      name: iOS Build
    #  runs-on: macos-latest
      runs-on: self-hosted
      steps:
        - name: Check out code
          uses: actions/checkout@v2

        - name: Install the Apple certificate and provisioning profile
          env:
            BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
            P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
            BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_NAG_BASE64 }}
            KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          run: |


            CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
            PP_PATH=$RUNNER_TEMP/American_Essentials_Travel_Hiremath-3.mobileprovision
            KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db


            echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
            echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

            echo $PP_PATH

            security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
            security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
            security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH

            security import $CERTIFICATE_PATH -P $P12_PASSWORD -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
            security list-keychains -d user -s $KEYCHAIN_PATH

            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
            chmod 777 ~/Library/MobileDevice/Provisioning\ Profiles/American_Essentials_Travel_Hiremath-3.mobileprovision
            ls ~/Library/MobileDevice/Provisioning\ Profiles/

            mkdir -p ~/_work/essentials-ui/essentials-ui/aae_mobile/ios/provfile
            cp $PP_PATH ~/_work/essentials-ui/essentials-ui/aae_mobile/ios/provfile
            chmod 777 ~/_work/essentials-ui/essentials-ui/aae_mobile/ios/provfile/American_Essentials_Travel_Hiremath-3.mobileprovision


        - name: copy generated dart files
          run: |
            cd ~/_work/essentials-ui/essentials-ui/aae_mobile/ios
            bundle install
            bundle update fastlane
            bundle exec fastlane newMachine

        - name: build ipa with fastlane
          run:  |
              cd ~/_work/essentials-ui/essentials-ui/aae_mobile/ios
              bundle exec fastlane beta

        - name: upload build files to artifact
          uses: actions/upload-artifact@v2
          with:
            name: AE ipa build
            path: ~/_work/essentials-ui/essentials-ui/aae_mobile/ios/build/


        - name: Clean up keychain and provisioning profile
          if: ${{ always() }}
          run: |
            security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
            rm -rf ~/Library/MobileDevice/Provisioning\ Profiles/*
            rm -rf ~/_work/essentials-ui/essentials-ui/aae_mobile/ios/provfile/*
